### ISSUE TITLE
Cannot find BGNA residue for chitin

### ISSUE THREAD

**Issue by daipayans** [soft-matter-theory-at-icmab-csic/chitin_builder#2]
Hi, 
In ForceField directory, the readme says "File with CHARMM36 carbohydrate force field parameters including chitin as BGNA residue." However, I cannot find the corresponding topology file with residue name BGNA.

**Comment by daipayans** [comment]
Ok, I see that the topology file is included in the structures sub-directory.

**Comment by jfaraudo** [comment]
Yes, this is explained in the documentaton.
