### ISSUE TITLE
Chitin Builder GUI's "Documentation..." item in Help menu links to a 404

### ISSUE THREAD

**Issue by amoeba** [soft-matter-theory-at-icmab-csic/chitin_builder#4]
While reviewing in #3, I noticed the "Documentation..." menu item under the Help menu in Chitin Builder opens my browser to https://bitbucket.org/icmab_soft_matter_theory/chitin_builder_gui/src/master/ which doesn't exist.

**Comment by amoeba** [comment]
I also noticed the PDF manual references BitBucket too so that may need a change.

**Comment by jfaraudo** [comment]
Corrected
